# Generated by Django 4.1.6 on 2025-08-24 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_phase_one', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_storage', models.BigIntegerField(default=0)),
                ('region', models.CharField(blank=True, choices=[('Mashhad', 'مشهد'), ('Quchan', 'قوچان'), ('Neyshabur', 'نیشابور')], max_length=50, null=True)),
                ('user_type', models.CharField(choices=[('Normal', 'کاربر عادی'), ('FieldManager', 'مدیر رشته')], default='Normal', max_length=20)),
                ('field', models.CharField(blank=True, choices=[('Literature', 'ادبیات و علوم انسانی'), ('LabSciences', 'آزمایشگاه علوم تجربی'), ('RoboticsAI', 'رباتیک و هوش مصنوعی'), ('Coding', 'کدنویسی'), ('Nanotechnology', 'نانوفناوری'), ('StemCells', 'سلول\u200cهای بنیادی'), ('SpaceTech', 'فناوری\u200cهای حوزه فضایی'), ('Astronomy', 'نجوم'), ('MedicinalPlants', 'گیاهان دارویی'), ('NuclearTech', 'علوم و فنون هسته\u200cای'), ('RenewableEnergy', 'انرژی\u200cهای نوین'), ('Biotechnology', 'زیست\u200cفناوری')], max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('field', models.CharField(choices=[('Literature', 'ادبیات و علوم انسانی'), ('LabSciences', 'آزمایشگاه علوم تجربی'), ('RoboticsAI', 'رباتیک و هوش مصنوعی'), ('Coding', 'کدنویسی'), ('Nanotechnology', 'نانوفناوری'), ('StemCells', 'سلول\u200cهای بنیادی'), ('SpaceTech', 'فناوری\u200cهای حوزه فضایی'), ('Astronomy', 'نجوم'), ('MedicinalPlants', 'گیاهان دارویی'), ('NuclearTech', 'علوم و فنون هسته\u200cای'), ('RenewableEnergy', 'انرژی\u200cهای نوین'), ('Biotechnology', 'زیست\u200cفناوری')], max_length=50)),
                ('size', models.BigIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
