# Generated by Django 4.1.6 on 2025-09-19 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_phase_one', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_storage', models.BigIntegerField(default=0)),
                ('region', models.CharField(blank=True, choices=[('JabirBinHayyanKarimi', 'جابربن حیان'), ('ZakariaRaziGholamPoor', 'زکریا رازی'), ('IbnSinaMansouri', 'ابن سینا'), ('DrHesabiAbdollahiZadeh', 'دکتر حسابی'), ('RaziAlizaiYousefAbadi', 'رازی'), ('Khwarizmi1ZareiZadehKasrini', 'خوارزمی1'), ('ThamenAlAimaSabzeBani', 'ثامن الائمه'), ('ValiAsrAlai', 'ولیعصر(عج)'), ('DrShafieiKadkaniRojabZadeh', 'دکتر شفیعی کدکنی'), ('KhwarizmiRahmatollahi', 'خوارزمی'), ('FerdowsiJahanBani', 'فردوسی'), ('DrHesabiKazemNejadKhalilAbad', 'دکتر حسابی'), ('IbnHeithamAzami', 'ابن هیثم'), ('AbuRayhanBiruniAhmadPoorMoghadam', 'ابوریحان بیرونی'), ('DrShariatiRoki', 'دکتر شریعتی'), ('AllamehShahrestaniJafari', 'علامه شهرستانی'), ('AbuRayhanRahimZadeh', 'ابوریحان'), ('ImamRezaNaderiFarmed', 'امام رضا (ع)'), ('JabirBinHayyanJavadi', 'جابربن حیان'), ('AsrarKohensal', 'اسرار'), ('AlaghemandanSoltani', 'علاقمندان'), ('ProfessorSadeghiSabouriHasanAbadi', 'پروفسورصادقی'), ('RaziShahbaniAwwal', 'رازی'), ('BagherAlOloum1Saadi', 'باقرالعلوم (ع) 1'), ('AyatollahKhameneiSoleimani', 'آیت الله خامنه ای'), ('ZakariayRaziNorouzi', 'زکریای رازی'), ('MoqedNiaAbbasZadeh', 'مقید نیا'), ('ShahidAhmadiRoshanKiani', 'شهید احمدی روشن'), ('JabirBinHayyanNooriMemarAbadi', 'جابربن حیان'), ('RaziAjami', 'رازی'), ('AbuRayhanMohammadianKalat', 'ابوریحان'), ('KatabiDarvishZadeh', 'کاتبی'), ('NimaSeyedAlHosseini', 'نیما'), ('ProphetAzamJinidi', 'پیامبر اعظم (ص)'), ('RaziAbdi', 'رازی'), ('AbuRayhanBiruniNokhai', 'ابوریحان بیرونی'), ('RoboticsRajabi', 'رباتیک'), ('FarhangHonarVaAdabParsiSabetFerdowsiRostgar', 'فرهنگ , هنر و ادب پارسی ثابت فردوسی'), ('MollaSadraMahki', 'ملاصدرا'), ('AllamehTabatabaeiVahidi', 'علامه طباطبایی'), ('DrHesabiHosseiniNik', 'دکتر حسابی'), ('FarabiYaqoubi', 'فارابی'), ('RaziRezapur', 'رازی'), ('RoyanBaratZadehYadgar', 'رویان'), ('BualiNobehar', 'بوعلی'), ('AndishehJalali', 'اندیشه'), ('SinaMasiHabadiHosseini', 'سینا مسیح آبادی'), ('MaalemShahidJalilRakhshaniNazariFard', 'معلم شهید جلیل رخشانی'), ('KhiyamFahimPoor', 'خیام')], max_length=50, null=True)),
                ('user_type', models.CharField(choices=[('Normal', 'کاربر عادی'), ('FieldManager', 'مدیر رشته')], default='Normal', max_length=20)),
                ('field', models.CharField(blank=True, choices=[('Literature', 'ادبیات و علوم انسانی'), ('LabSciences', 'آزمایشگاه علوم تجربی'), ('RoboticsAI', 'رباتیک و هوش مصنوعی'), ('Coding', 'کدنویسی'), ('Nanotechnology', 'نانوفناوری'), ('StemCells', 'سلول\u200cهای بنیادی'), ('SpaceTech', 'فناوری\u200cهای حوزه فضایی'), ('Astronomy', 'نجوم'), ('MedicinalPlants', 'گیاهان دارویی'), ('NuclearTech', 'علوم و فنون هسته\u200cای'), ('RenewableEnergy', 'انرژی\u200cهای نوین'), ('Biotechnology', 'زیست\u200cفناوری')], max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('field', models.CharField(choices=[('Literature', 'ادبیات و علوم انسانی'), ('LabSciences', 'آزمایشگاه علوم تجربی'), ('RoboticsAI', 'رباتیک و هوش مصنوعی'), ('Coding', 'کدنویسی'), ('Nanotechnology', 'نانوفناوری'), ('StemCells', 'سلول\u200cهای بنیادی'), ('SpaceTech', 'فناوری\u200cهای حوزه فضایی'), ('Astronomy', 'نجوم'), ('MedicinalPlants', 'گیاهان دارویی'), ('NuclearTech', 'علوم و فنون هسته\u200cای'), ('RenewableEnergy', 'انرژی\u200cهای نوین'), ('Biotechnology', 'زیست\u200cفناوری')], max_length=50)),
                ('size', models.BigIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
